include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  errors:
    todo: info
    avoid_print: ignore

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - annotate_overrides
    #- avoid_print
    - prefer_single_quotes
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_collection_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_this
    - omit_local_variable_types
    - curly_braces_in_flow_control_structures
    - constant_identifier_names
    - camel_case_types
    - file_names
